spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: myTcc
  tcc:
    storage:
      storage-type: remoting
      domain: "TCC:FEIGN:CAPITAL"
    recovery:
      recovery-enabled: false
    registry:
      registry-type: direct
      cluster-name: default
      direct:
        server-addresses: 192.168.44.228:2332
server:
  port: 8082
  servlet:
    context-path: /myTcc
logging:
  level:
    root: info